# This file controls the settings for your Quarto template from www.marvinschmitt.com

# website settings
website:
  title: "Monica Ghosh"                                # Your name
  description: "Gandalf is a renowned wizard and scholar of Middle-earth"   # A brief slogan (optional)
  image: img/my_image.jpg
  
  favicon: img/case_logo.png
  
  # start of the navigation bar at the top of the website
  navbar:
    pinned: true
    logo: /img/case_logo.png
    
    # your sub-pages
    left:
      - text: "Education"
        href: education/index.qmd
      - text: "Research"
        href: research/index.qmd
      - text: "Interests"
        href: interest/index.qmd
      - text: "CV"
        href: cv/index.qmd
    
    # your social media handles
    right:

      - icon: linkedin
        text: Linkedin
        href: https://www.linkedin.com/in/monicaghosh/
      - icon: instagram
        text: Instagram
        href: https://www.instagram.com/thekolkatacook/
      - icon: envelope
        aria-label: email
        text: Email
        href: "mailto:mxg979@case.edu"  
  
  

# Don't touch unless you know what you are doing :) ------------
  search: 
    location: navbar
    type: overlay

project:
  type: website
  output-dir: docs

  preview: 
    port: 22222
    browser: true
    watch-inputs: true
    navigate: true

execute:
  freeze: true

format:
  html:
    fontsize: 1.1em
    theme: 
      - pulse
      - html/styles.scss
    toc: false
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true